import { TaskPriority } from "@/types";

export const priority: { title: TaskPriority; _id: string; color: string }[] = [
    {
        title: TaskPriority.LOW,
        _id: "LOW_ID",
        color: "#016e2d",
    },
    {
        title: TaskPriority.MED,
        color: "#FFD700",
        _id: "MED_ID",
    },
    {
        title: TaskPriority.HIGH,
        color: "#fa1302",
        _id: "HIGH_ID",
    },
];

export const tags = [
    {
        _id: "backlog",
        title: "Backlog",
        color: "#f3a683",
    },
    {
        _id: "todo",
        title: "Todo",
        color: "#f7d794",
    },
    {
        _id: "in progress",
        title: "In Progress",
        color: "#778beb",
    },
    {
        _id: "done",
        title: "Done",
        color: "#e77f67",
    },
    {
        _id: "canceled",
        title: "Canceled",
        color: "#cf6a87",
    },
];

export const UserDetails = [
    {
        _id: "1",
        firstName: "John",
        lastName: "Doe",
        username: "johndoe",
        email: "john.doe@example.com",
        emailVerified: true,
        role: "user",
        deactivated: false,
        deleted: false,
        profilePicture: "https://randomuser.me/api/portraits/men/1.jpg",
    },
    {
        _id: "2",
        firstName: "Jane",
        lastName: "Smith",
        username: "janesmith",
        email: "jane.smith@example.com",
        emailVerified: true,
        role: "user",
        deactivated: false,
        deleted: false,
        profilePicture: "https://randomuser.me/api/portraits/women/2.jpg",
    },
    {
        _id: "3",
        firstName: "Michael",
        lastName: "Johnson",
        username: "michaeljohnson",
        email: "michael.johnson@example.com",
        emailVerified: true,
        role: "user",
        deactivated: false,
        deleted: false,
        profilePicture: "https://randomuser.me/api/portraits/men/3.jpg",
    },
    {
        _id: "4",
        firstName: "Emily",
        lastName: "Brown",
        username: "emilybrown",
        email: "emily.brown@example.com",
        emailVerified: true,
        role: "user",
        deactivated: false,
        deleted: false,
        profilePicture: "https://randomuser.me/api/portraits/women/4.jpg",
    },
    {
        _id: "5",
        firstName: "Daniel",
        lastName: "Wilson",
        username: "danielwilson",
        email: "daniel.wilson@example.com",
        emailVerified: true,
        role: "user",
        deactivated: false,
        deleted: false,
        profilePicture: "https://randomuser.me/api/portraits/men/5.jpg",
    },
    {
        _id: "6",
        firstName: "Olivia",
        lastName: "Martinez",
        username: "oliviamartinez",
        email: "olivia.martinez@example.com",
        emailVerified: true,
        role: "user",
        deactivated: false,
        deleted: false,
        profilePicture: "https://randomuser.me/api/portraits/women/6.jpg",
    },
    {
        _id: "7",
        firstName: "David",
        lastName: "Lopez",
        username: "davidlopez",
        email: "david.lopez@example.com",
        emailVerified: true,
        role: "user",
        deactivated: false,
        deleted: false,
        profilePicture: "https://randomuser.me/api/portraits/men/7.jpg",
    },
    {
        _id: "8",
        firstName: "Emma",
        lastName: "Garcia",
        username: "emmagarcia",
        email: "emma.garcia@example.com",
        emailVerified: true,
        role: "user",
        deactivated: false,
        deleted: false,
        profilePicture: "https://randomuser.me/api/portraits/women/8.jpg",
    },
    {
        _id: "9",
        firstName: "James",
        lastName: "Martinez",
        username: "jamesmartinez",
        email: "james.martinez@example.com",
        emailVerified: true,
        role: "user",
        deactivated: false,
        deleted: false,
        profilePicture: "https://randomuser.me/api/portraits/men/9.jpg",
    },
    {
        _id: "10",
        firstName: "Ava",
        lastName: "Young",
        username: "avayoung",
        email: "ava.young@example.com",
        emailVerified: true,
        role: "user",
        deactivated: false,
        deleted: false,
        profilePicture: "https://randomuser.me/api/portraits/women/10.jpg",
    },
];
